/*
 * Icon Lookup Helper
 * Maps icon names to UTF-8 encoded Material Design Icons glyphs
 * Auto-generated from icons.json - DO NOT EDIT MANUALLY
 */

#include "icon_lookup.h"
#include "material_icons.h"
#include <string.h>

// Icon name to UTF-8 glyph mapping
struct IconMapping {
  const char* name;
  const char* glyph;
};

// Icon lookup table (auto-generated, sorted alphabetically)
static const IconMapping ICON_LOOKUP_TABLE[] = {
  {"account", ICON_ACCOUNT},
  {"account-circle", ICON_ACCOUNT_CIRCLE},
  {"account-group", ICON_ACCOUNT_GROUP},
  {"account-multiple", ICON_ACCOUNT_MULTIPLE},
  {"account-outline", ICON_ACCOUNT_OUTLINE},
  {"alarm", ICON_ALARM},
  {"alarm-check", ICON_ALARM_CHECK},
  {"alert", ICON_ALERT},
  {"alert-circle", ICON_ALERT_CIRCLE},
  {"alert-outline", ICON_ALERT_OUTLINE},
  {"application", ICON_APPLICATION},
  {"application-braces", ICON_APPLICATION_BRACES},
  {"application-brackets", ICON_APPLICATION_BRACKETS},
  {"apps", ICON_APPS},
  {"arrow-down", ICON_ARROW_DOWN},
  {"arrow-down-bold", ICON_ARROW_DOWN_BOLD},
  {"arrow-down-circle", ICON_ARROW_DOWN_CIRCLE},
  {"arrow-left", ICON_ARROW_LEFT},
  {"arrow-left-bold", ICON_ARROW_LEFT_BOLD},
  {"arrow-left-circle", ICON_ARROW_LEFT_CIRCLE},
  {"arrow-right", ICON_ARROW_RIGHT},
  {"arrow-right-bold", ICON_ARROW_RIGHT_BOLD},
  {"arrow-right-circle", ICON_ARROW_RIGHT_CIRCLE},
  {"arrow-up", ICON_ARROW_UP},
  {"arrow-up-bold", ICON_ARROW_UP_BOLD},
  {"arrow-up-circle", ICON_ARROW_UP_CIRCLE},
  {"backspace", ICON_BACKSPACE},
  {"barcode", ICON_BARCODE},
  {"battery", ICON_BATTERY},
  {"battery-alert", ICON_BATTERY_ALERT},
  {"battery-charging", ICON_BATTERY_CHARGING},
  {"bell", ICON_BELL},
  {"bell-off", ICON_BELL_OFF},
  {"bell-outline", ICON_BELL_OUTLINE},
  {"bluetooth", ICON_BLUETOOTH},
  {"bluetooth-off", ICON_BLUETOOTH_OFF},
  {"bookmark", ICON_BOOKMARK},
  {"brightness-5", ICON_BRIGHTNESS_5},
  {"brightness-6", ICON_BRIGHTNESS_6},
  {"brush", ICON_BRUSH},
  {"bug", ICON_BUG},
  {"calculator", ICON_CALCULATOR},
  {"calendar", ICON_CALENDAR},
  {"calendar-outline", ICON_CALENDAR_OUTLINE},
  {"camera", ICON_CAMERA},
  {"camera-outline", ICON_CAMERA_OUTLINE},
  {"cellphone", ICON_CELLPHONE},
  {"chat", ICON_CHAT},
  {"chat-outline", ICON_CHAT_OUTLINE},
  {"check", ICON_CHECK},
  {"check-circle", ICON_CHECK_CIRCLE},
  {"check-circle-outline", ICON_CHECK_CIRCLE_OUTLINE},
  {"chevron-double-down", ICON_CHEVRON_DOUBLE_DOWN},
  {"chevron-double-left", ICON_CHEVRON_DOUBLE_LEFT},
  {"chevron-double-right", ICON_CHEVRON_DOUBLE_RIGHT},
  {"chevron-double-up", ICON_CHEVRON_DOUBLE_UP},
  {"chevron-down", ICON_CHEVRON_DOWN},
  {"chevron-left", ICON_CHEVRON_LEFT},
  {"chevron-right", ICON_CHEVRON_RIGHT},
  {"chevron-up", ICON_CHEVRON_UP},
  {"clock", ICON_CLOCK},
  {"clock-outline", ICON_CLOCK_OUTLINE},
  {"close", ICON_CLOSE},
  {"close-circle", ICON_CLOSE_CIRCLE},
  {"close-circle-outline", ICON_CLOSE_CIRCLE_OUTLINE},
  {"cloud", ICON_CLOUD},
  {"cloud-download", ICON_CLOUD_DOWNLOAD},
  {"cloud-upload", ICON_CLOUD_UPLOAD},
  {"code-braces", ICON_CODE_BRACES},
  {"code-brackets", ICON_CODE_BRACKETS},
  {"code-tags", ICON_CODE_TAGS},
  {"cog", ICON_COG},
  {"cog-outline", ICON_COG_OUTLINE},
  {"comment", ICON_COMMENT},
  {"comment-outline", ICON_COMMENT_OUTLINE},
  {"compass", ICON_COMPASS},
  {"console", ICON_CONSOLE},
  {"content-copy", ICON_CONTENT_COPY},
  {"content-cut", ICON_CONTENT_CUT},
  {"content-paste", ICON_CONTENT_PASTE},
  {"content-save", ICON_CONTENT_SAVE},
  {"database", ICON_DATABASE},
  {"delete", ICON_DELETE},
  {"delete-forever", ICON_DELETE_FOREVER},
  {"delete-outline", ICON_DELETE_OUTLINE},
  {"dots-grid", ICON_DOTS_GRID},
  {"dots-horizontal", ICON_DOTS_HORIZONTAL},
  {"dots-vertical", ICON_DOTS_VERTICAL},
  {"download", ICON_DOWNLOAD},
  {"earth", ICON_EARTH},
  {"email", ICON_EMAIL},
  {"email-open", ICON_EMAIL_OPEN},
  {"email-outline", ICON_EMAIL_OUTLINE},
  {"export", ICON_EXPORT},
  {"eye", ICON_EYE},
  {"fast-forward", ICON_FAST_FORWARD},
  {"file", ICON_FILE},
  {"file-code", ICON_FILE_CODE},
  {"file-document", ICON_FILE_DOCUMENT},
  {"file-document-outline", ICON_FILE_DOCUMENT_OUTLINE},
  {"file-download", ICON_FILE_DOWNLOAD},
  {"file-edit", ICON_FILE_EDIT},
  {"file-excel", ICON_FILE_EXCEL},
  {"file-image", ICON_FILE_IMAGE},
  {"file-music", ICON_FILE_MUSIC},
  {"file-outline", ICON_FILE_OUTLINE},
  {"file-pdf-box", ICON_FILE_PDF_BOX},
  {"file-plus", ICON_FILE_PLUS},
  {"file-powerpoint", ICON_FILE_POWERPOINT},
  {"file-search", ICON_FILE_SEARCH},
  {"file-upload", ICON_FILE_UPLOAD},
  {"file-video", ICON_FILE_VIDEO},
  {"file-word", ICON_FILE_WORD},
  {"fingerprint", ICON_FINGERPRINT},
  {"flag", ICON_FLAG},
  {"flash", ICON_FLASH},
  {"flash-off", ICON_FLASH_OFF},
  {"folder", ICON_FOLDER},
  {"folder-download", ICON_FOLDER_DOWNLOAD},
  {"folder-edit", ICON_FOLDER_EDIT},
  {"folder-image", ICON_FOLDER_IMAGE},
  {"folder-music", ICON_FOLDER_MUSIC},
  {"folder-open", ICON_FOLDER_OPEN},
  {"folder-plus", ICON_FOLDER_PLUS},
  {"folder-upload", ICON_FOLDER_UPLOAD},
  {"format-align-center", ICON_FORMAT_ALIGN_CENTER},
  {"format-align-justify", ICON_FORMAT_ALIGN_JUSTIFY},
  {"format-align-left", ICON_FORMAT_ALIGN_LEFT},
  {"format-align-right", ICON_FORMAT_ALIGN_RIGHT},
  {"format-bold", ICON_FORMAT_BOLD},
  {"format-clear", ICON_FORMAT_CLEAR},
  {"format-color-fill", ICON_FORMAT_COLOR_FILL},
  {"format-color-text", ICON_FORMAT_COLOR_TEXT},
  {"format-indent-decrease", ICON_FORMAT_INDENT_DECREASE},
  {"format-indent-increase", ICON_FORMAT_INDENT_INCREASE},
  {"format-italic", ICON_FORMAT_ITALIC},
  {"format-list-bulleted", ICON_FORMAT_LIST_BULLETED},
  {"format-list-numbered", ICON_FORMAT_LIST_NUMBERED},
  {"format-paint", ICON_FORMAT_PAINT},
  {"format-quote-close", ICON_FORMAT_QUOTE_CLOSE},
  {"format-size", ICON_FORMAT_SIZE},
  {"format-strikethrough", ICON_FORMAT_STRIKETHROUGH},
  {"format-subscript", ICON_FORMAT_SUBSCRIPT},
  {"format-superscript", ICON_FORMAT_SUPERSCRIPT},
  {"format-text", ICON_FORMAT_TEXT},
  {"format-underline", ICON_FORMAT_UNDERLINE},
  {"forum", ICON_FORUM},
  {"hammer", ICON_HAMMER},
  {"headphones", ICON_HEADPHONES},
  {"heart", ICON_HEART},
  {"heart-outline", ICON_HEART_OUTLINE},
  {"help", ICON_HELP},
  {"help-circle", ICON_HELP_CIRCLE},
  {"help-circle-outline", ICON_HELP_CIRCLE_OUTLINE},
  {"home", ICON_HOME},
  {"home-circle", ICON_HOME_CIRCLE},
  {"image", ICON_IMAGE},
  {"image-outline", ICON_IMAGE_OUTLINE},
  {"import", ICON_IMPORT},
  {"information", ICON_INFORMATION},
  {"information-outline", ICON_INFORMATION_OUTLINE},
  {"keyboard", ICON_KEYBOARD},
  {"laptop", ICON_LAPTOP},
  {"lightbulb", ICON_LIGHTBULB},
  {"lightbulb-outline", ICON_LIGHTBULB_OUTLINE},
  {"link", ICON_LINK},
  {"link-off", ICON_LINK_OFF},
  {"lock", ICON_LOCK},
  {"lock-open", ICON_LOCK_OPEN},
  {"magnify", ICON_MAGNIFY},
  {"magnify-close", ICON_MAGNIFY_CLOSE},
  {"magnify-minus", ICON_MAGNIFY_MINUS},
  {"magnify-plus", ICON_MAGNIFY_PLUS},
  {"map", ICON_MAP},
  {"map-marker", ICON_MAP_MARKER},
  {"menu", ICON_MENU},
  {"menu-down", ICON_MENU_DOWN},
  {"menu-left", ICON_MENU_LEFT},
  {"menu-open", ICON_MENU_OPEN},
  {"menu-right", ICON_MENU_RIGHT},
  {"menu-up", ICON_MENU_UP},
  {"message", ICON_MESSAGE},
  {"message-outline", ICON_MESSAGE_OUTLINE},
  {"message-text", ICON_MESSAGE_TEXT},
  {"microphone", ICON_MICROPHONE},
  {"microphone-off", ICON_MICROPHONE_OFF},
  {"minus", ICON_MINUS},
  {"minus-circle", ICON_MINUS_CIRCLE},
  {"minus-circle-outline", ICON_MINUS_CIRCLE_OUTLINE},
  {"monitor", ICON_MONITOR},
  {"mouse", ICON_MOUSE},
  {"music", ICON_MUSIC},
  {"music-box", ICON_MUSIC_BOX},
  {"palette", ICON_PALETTE},
  {"pause", ICON_PAUSE},
  {"pause-circle", ICON_PAUSE_CIRCLE},
  {"pencil", ICON_PENCIL},
  {"pencil-outline", ICON_PENCIL_OUTLINE},
  {"phone", ICON_PHONE},
  {"phone-outline", ICON_PHONE_OUTLINE},
  {"play", ICON_PLAY},
  {"play-circle", ICON_PLAY_CIRCLE},
  {"play-pause", ICON_PLAY_PAUSE},
  {"plus", ICON_PLUS},
  {"plus-circle", ICON_PLUS_CIRCLE},
  {"plus-circle-outline", ICON_PLUS_CIRCLE_OUTLINE},
  {"power", ICON_POWER},
  {"power-off", ICON_POWER_OFF},
  {"qrcode", ICON_QRCODE},
  {"record", ICON_RECORD},
  {"redo", ICON_REDO},
  {"refresh", ICON_REFRESH},
  {"refresh-circle", ICON_REFRESH_CIRCLE},
  {"replay", ICON_REPLAY},
  {"restart", ICON_RESTART},
  {"restore", ICON_RESTORE},
  {"rewind", ICON_REWIND},
  {"screwdriver", ICON_SCREWDRIVER},
  {"send", ICON_SEND},
  {"send-circle", ICON_SEND_CIRCLE},
  {"server", ICON_SERVER},
  {"settings", ICON_SETTINGS},
  {"share", ICON_SHARE},
  {"share-variant", ICON_SHARE_VARIANT},
  {"shield", ICON_SHIELD},
  {"shield-check", ICON_SHIELD_CHECK},
  {"skip-next", ICON_SKIP_NEXT},
  {"skip-previous", ICON_SKIP_PREVIOUS},
  {"sleep", ICON_SLEEP},
  {"speaker", ICON_SPEAKER},
  {"speaker-off", ICON_SPEAKER_OFF},
  {"star", ICON_STAR},
  {"star-half", ICON_STAR_HALF},
  {"star-outline", ICON_STAR_OUTLINE},
  {"stop", ICON_STOP},
  {"stop-circle", ICON_STOP_CIRCLE},
  {"swap-horizontal", ICON_SWAP_HORIZONTAL},
  {"swap-vertical", ICON_SWAP_VERTICAL},
  {"sync", ICON_SYNC},
  {"tag", ICON_TAG},
  {"tag-multiple", ICON_TAG_MULTIPLE},
  {"text-box", ICON_TEXT_BOX},
  {"thumb-down", ICON_THUMB_DOWN},
  {"thumb-up", ICON_THUMB_UP},
  {"timer", ICON_TIMER},
  {"timer-outline", ICON_TIMER_OUTLINE},
  {"trash-can", ICON_TRASH_CAN},
  {"tune", ICON_TUNE},
  {"undo", ICON_UNDO},
  {"upload", ICON_UPLOAD},
  {"video", ICON_VIDEO},
  {"video-outline", ICON_VIDEO_OUTLINE},
  {"volume-high", ICON_VOLUME_HIGH},
  {"volume-low", ICON_VOLUME_LOW},
  {"volume-medium", ICON_VOLUME_MEDIUM},
  {"volume-mute", ICON_VOLUME_MUTE},
  {"volume-off", ICON_VOLUME_OFF},
  {"web", ICON_WEB},
  {"wifi", ICON_WIFI},
  {"wifi-off", ICON_WIFI_OFF},
  {"wrench", ICON_WRENCH},
};

static const int ICON_LOOKUP_TABLE_SIZE = sizeof(ICON_LOOKUP_TABLE) / sizeof(IconMapping);

const char* icon_lookup(const char* icon_name) {
  if (!icon_name || strlen(icon_name) == 0) {
    return nullptr;
  }
  
  // Linear search (250 icons is small enough, binary search not needed)
  for (int i = 0; i < ICON_LOOKUP_TABLE_SIZE; i++) {
    if (strcmp(icon_name, ICON_LOOKUP_TABLE[i].name) == 0) {
      return ICON_LOOKUP_TABLE[i].glyph;
    }
  }
  
  return nullptr;  // Icon not found
}
